pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    bash <(curl https://nixos.org/nix/install)
    source ~/.nix-profile/etc/profile.d/nix.sh
    nix-env -iA nixpkgs.nixops -iA nixpkgs.openssh
    mkdir -p $HOME/.config/nix
    echo "substituters = https://cache.nixos.org https://snix.ovh" > $HOME/.config/nix/nix.conf
    echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= snix.ovh:ALIRUOtoiM/NKfVaL+I+AFU9/BYDOqBbm081csf8Xz0=" >> $HOME/.config/nix/nix.conf
    
  displayName: 'Setup Nix Package Manager'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '116.203.231.139 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDZyPjWgDrpXnqvVuJkQLNeW3qn6s+gaHuKqBwu+86nm++3fGA0udysQ2ZtdYPb0fbi+mcuHHqVzGsvOpJC0vAeE3tCmvslJMSS9rmXQ4m0NfaeTtMGNWG13PvTtwdUFirRnvApn5dR6GRU13R1yTnFKRbnOahs3AAD1ke2g5IJYn9Av0yH9TIMl/Cddb1lw3bGm8dFRav2hs6fyET2hfcYA56ipWQKhUclhzi8OtkY2XPW9WWCPA6eMHEyUUcWdQW03E1T9J3/CwAf+v6ptGW9qXrDuLtumIkrWCCZQxuMG8sCIJL/YQg0LDU6lwA3wREN/TP4+Z57d5l/z151pk4sKTPI1oGYUzvlBwqfciGybrkiyIGFju2EQkjbZNB0/ZHJLOHqJqVPZvPDOyWcudAlU+J5IzxXt2rjJh0AKhVkuRtyQIK7KCR/YNXsrEfz42VrVzpSO2LVGCxm3kTjxBar83yDTERbf3u3VQXMbbY+DHTt7ygaCvaBW8n8gBD7JZW4vcNvssl1qfPEV+38QHxFAUfgnlT9P0SqD4HhYbGvf1EGdfC6xXdA081r8221/vbNypPOAD2rJ7gnA0vLkUWvWrEdBCuH5lBKv1raOBvFmU0TjF+g5/7XY3E1PTeA7n3GsayW429TYLAvfDIvv9AbY9/9Nk6caBt8c8AqHUEnEQ=='
    sshKeySecureFile: 'deploy.key'
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZ+aKMtUKvQn2jG8KaZGhWOx1TUNTcrE9i9YhAaNfpGKGF7yQHNdAKjtdfIPkaSpsXAGljMbXsXHgp7UbH7op8FFYVRZcjY+3aR3U82eqp5D/MWWgXEB/w50fpQu4sie7PDoJGm6NYdxHPinvA5a+ozN3EGQsRwGAFQlbRYfo2TZLkYMhZWIoapEKz34N/dEXA7u1MMzflAZQ3aUE/Wme+cKwCpILF9k7GxtWmw6On01o7sngHt2FFw3KFEwTKJQbWnjgGALHFNpz/acYCqCtABXfaaU9jmDLn9zOfT8ZkggEn3plDIZssShaGZlAnnvzlpVQ7GffES+uMr36lUvHp shyim@shiina'

- script: |
    source ~/.nix-profile/etc/profile.d/nix.sh
    nixops create -d yuno ./devices/yuno.nix
    nixops deploy -d yuno
    
  displayName: 'Deploy to yuno'
